### ISSUE TITLE
Question about your library flixpy

### ISSUE THREAD

**Issue by ninest** [chrisdrackett/django-typogrify#18]
Firstly, my apologies for making an issue here. I wasn't sure of how else to co tact you.

Would you be willing to transfer the project name Flixpy in Pypi to me?

https://pypi.org/project/flixpy/

I'd like to make a library for movies. Currently, the Netflix API is deprecated, and the Flixpy library received it's last update in 2012. Thanks.

**Comment by ninest** [comment]
Thank you!

**Comment by chrisdrackett** [comment]
@ninest do you have the ability to remove me from the project? I don't seem to be able to leave :D

**Comment by ninest** [comment]
Ah, yes, I removed you. Thanks :)
